Fixes for Intel 2024.2
GEOSgcm (and thus GEOSadas) will soon move to use Intel oneAPI 2024.2
which is Intel `ifort` 2021.13 and `icx` 2024.2.

Tests showed two issues. First there was a plain Fortran bug in
`GMAO_ods/ods_diagnc4.F90`:

```fortran
     ods%data%time(1:nobs) = int(rvals * 60,)
```

That trailing comma is just wrong.

`icx` also threw an error with some C code:

```
/discover/swdev/mathomp4/Models/GEOSadas-MAPLdevelop-Baselibs-7.25.0/src/Shared/@GMAO_Shared/GMAO_pyobs/VegType_io.c:17:5: error: call to undeclared library function 'exit' with type 'void (int) __attribute__((noreturn))'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   17 |     exit(1);
      |     ^
/discover/swdev/mathomp4/Models/GEOSadas-MAPLdevelop-Baselibs-7.25.0/src/Shared/@GMAO_Shared/GMAO_pyobs/VegType_io.c:17:5: note: include the header <stdlib.h> or explicitly provide a declaration for 'exit'
```

As the error states, we add `#include <stdlib.h>`